# -*- coding: utf-8 -*-
"""Calculos inventario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_6ULUwKWoOIjfDGeAPiRaHVgnM7moYI
"""

# @title Importación de Librerias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# @title Muestra básico de calculo
ConsumoNominal = 0.22
FactorDeCarga = 0.8
TiempoDeUso = 156
CantidadEquipos = 10
Eficiencia = 0.82
CostoUnitario = 19.45
EnergiaConsumida = TiempoDeUso * FactorDeCarga * CantidadEquipos * ConsumoNominal / Eficiencia
print("Energia Consumida",round(EnergiaConsumida, 2),"kWh")
EnergiaUtilConsumida = TiempoDeUso * FactorDeCarga * CantidadEquipos * ConsumoNominal * Eficiencia
print("Energia Util Consumida",round(EnergiaUtilConsumida, 2),"kWh")
CostoValorUnitario= EnergiaConsumida * CostoUnitario
print("Costo Valor Unitario",round(CostoValorUnitario, 2),"$/kWh")
EnergiaUtilConsumida = TiempoDeUso * FactorDeCarga * CantidadEquipos * ConsumoNominal * Eficiencia
print("Energia Util Consumida",round(EnergiaUtilConsumida, 2),"kWh")
CostoValorUnitario= EnergiaConsumida * CostoUnitario
print("Costo Valor Unitario",round(CostoValorUnitario, 2),"$/kWh")

"""Aplicar las ecuaciones en forma general"""

# @title Parametrización de Datos de la tabla de Factor de Carga y Eficiencia - Formato estandar && no definitivo -  INVESTIGAR
import pandas as pd

data = {
    'Tipo de proceso': ['Motor', 'Resistencia', 'Electrónico', 'Motor & Resistencia', 'Magnetrón', 'Electroluminiscencia'],
    'Factor de Carga': [0.7, 1, 0.7, 0.8, 0.7, 1],
    'Eficiencia': [0.9, 0.6, 0.8, 0.82, 0.6, 0.9]
}

tablaFQE = pd.DataFrame(data)
print(tablaFQE)

# @title Carga de datos del Inventario

from google.colab import drive
drive.mount('/content/drive')
inventario_df = pd.read_excel('/content/drive/MyDrive/Modo Ahorro - Proyecto /Calculos/Calculos inventarios/inventario.xlsx')
print(inventario_df.head())

# @title Mergue con Uso y tipo de proceso para normalizar Factor de Carga y Eficiencia - INVESTIGAR SI ESTÁ BIEN
inventario = pd.merge(inventario_df, tablaFQE, on='Tipo de proceso', how='left' )
inventario.head()

# @title Cálculo de Energía Secundaria Consumida
inventario['Energia Secundaria Consumida'] = round((inventario['Horas de uso [h/año]'] * inventario['Factor de Carga']* inventario['Cantidad de equipos'] * inventario['Consumo Nominal']) / inventario['Eficiencia'], 2)
inventario

# @title Cálculo de Energía Útil Consumida
inventario['Energia Util Consumida'] = inventario['Horas de uso [h/año]'] * inventario['Factor de Carga']* inventario['Cantidad de equipos'] * inventario['Consumo Nominal']
inventario

# @title Distibución del consumo nominal
custom_palette = sns.color_palette("pastel")
sns.histplot(data=inventario, x='Consumo Nominal', bins=15, color=custom_palette[0])
plt.title('Distribución del consumo nominal')
plt.xlabel('Consumo Nominal (en la unidad correspondiente)')
plt.ylabel('Frecuencia')

sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# @title Distibución de equipos por dispositivos
custom_palette = sns.color_palette("pastel")
sns.histplot(data=inventario, x='Cantidad de equipos', bins=15, color=custom_palette[0])
plt.title('Distribución de equipos por dispositivo')
plt.xlabel('Cantidad de equipos')
plt.ylabel('Frecuencia')

sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# @title Distribución de horas de uso anual
custom_palette = sns.color_palette("deep")
sns.histplot(data=inventario, x='Horas de uso [h/año]', bins=15, color=custom_palette[0])
plt.title('Distribución de horas de uso anual')
plt.xlabel('Horas de uso por año')
plt.ylabel('Frecuencia')
sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# @title Distribución de Factor de Carga
custom_palette = sns.color_palette("coolwarm")
sns.histplot(data=inventario, x='Factor de Carga', bins=15, color=custom_palette[4])
plt.title('Distribución del Factor de Carga')
plt.xlabel('Factor de Carga')
plt.ylabel('Frecuencia')
sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# @title Cantidad de Equipos según su Uso
inventario.groupby('Uso)').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)
for p in plt.gca().patches:
    plt.gca().annotate(f'{p.get_width()}', (p.get_width() + 0.5, p.get_y() + p.get_height() / 2), ha='center', va='center')
plt.gca().spines['bottom'].set_linewidth(1.5)
plt.gca().spines['left'].set_linewidth(1.5)
plt.gca().tick_params(axis='both', which='major', labelsize=12)
plt.xticks([])

# @title Cantidad de equipos según su tipo de proceso
inventario.groupby('Tipo de proceso').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)
for p in plt.gca().patches:
    plt.gca().annotate(f'{p.get_width()}', (p.get_width() + 0.5, p.get_y() + p.get_height() / 2), ha='center', va='center')
plt.gca().spines['bottom'].set_linewidth(1.5)
plt.gca().spines['left'].set_linewidth(1.5)
plt.gca().tick_params(axis='both', which='major', labelsize=12)
plt.xticks([])

# @title Gráfico de dispersión, intepretación de rangos de consumos
bins = [0, 1, 2, float('inf')]
labels = ['Low', 'Medium', 'High']
inventario['Rango de consumo'] = pd.cut(inventario['Consumo Nominal'], bins=bins, labels=labels)
sns.set_style("whitegrid")
sns.set_palette("husl")
plt.figure(figsize=(8, 6))
sns.scatterplot(data=inventario, x='Consumo Nominal', y='Cantidad de equipos', hue='Rango de consumo', size='Consumo Nominal', alpha=0.7)
plt.title('Distribución de equipos por consumo nominal')
plt.xlabel('Consumo Nominal')
plt.ylabel('Cantidad de equipos')
plt.legend(title='Rango de consumo')
plt.gca().spines[['top', 'right',]].set_visible(False)
plt.axvline(x=1, color='gray', linestyle='--')
plt.show()

# @title Tipo de proceso
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Tipo de proceso'].value_counts()
    for x_label, grp in inventario.groupby('Uso)')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Uso)')
_ = plt.ylabel('Tipo de proceso')

# @title Grafico tipo Violín  sobre tipo de proceso y su consumo nominal
figsize = (12, 1.2 * len(inventario['Tipo de proceso'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario, x='Consumo Nominal', y='Tipo de proceso', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title Grafico tipo Violín sobre Uso y su consumo nominal
figsize = (12, 1.2 * len(inventario['Uso)'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario, x='Consumo Nominal', y='Uso)', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title Grafico tipo Violín sobre Uso y su cantidad de equipos
figsize = (12, 1.2 * len(inventario['Uso)'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario, x='Cantidad de equipos', y='Uso)', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

#@title Grafico tipo Violín sobre tipo de proceso y su cantidad de equipos
figsize = (12, 1.2 * len(inventario['Tipo de proceso'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario, x='Cantidad de equipos', y='Tipo de proceso', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

# @title Asumiento que el CostoUnitario = $ 19.45 basado en datos de las 12 boletas, implementamos los valores aproximados
inventario['Costo $ Consumo'] = round(inventario['Energia Secundaria Consumida'] * CostoUnitario, 2)
inventario

# @title .
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Consumo Nominal', y='Costo $ Consumo', data=inventario)
plt.xlabel('Consumo Nominal (kW)')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Consumo Nominal y Costo de Consumo')
plt.show()

# @title .

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(data=inventario, x='Consumo Nominal', y='Costo $ Consumo', hue='Tipo de proceso')
plt.xlabel('Nominal Consumption')
plt.ylabel('Energy Cost ($)')
_ = plt.title('Consumo Nominal vs. Costo de Energía por Tipo de Equipo')

# @title .
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Cantidad de equipos', y='Costo $ Consumo', data=inventario)
plt.xlabel('Cantidad de equipos')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Cantidad de equipos y Costo de Consumo')
plt.show()

# @title .
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Horas de uso [h/año]', y='Costo $ Consumo', data=inventario)
plt.xlabel('Horas de uso [h/año]')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Horas de uso y Costo de Consumo')
plt.show()

# @title .
plt.figure(figsize=(10, 6))
sns.boxplot(x='Tipo de proceso', y='Costo $ Consumo', data=inventario)
plt.xlabel('Tipo de proceso')
plt.ylabel('Costo $ Consumo')
plt.title('Costo de Consumo por Tipo de proceso')
plt.xticks(rotation=45, ha='right')
plt.show()

# @title .
plt.figure(figsize=(10, 6))
sns.boxplot(x='Uso)', y='Costo $ Consumo', data=inventario)
plt.xlabel('Uso)')
plt.ylabel('Costo $ Consumo')
plt.title('Costo de Consumo por Uso)')
plt.xticks(rotation=45, ha='right')
plt.show()

# @title DESCARGA DE INVENTARIO CON CALCULOS - modificar valor de descarga por "Si" y ejecutar
descargar="No"
if descargar=="Si":
  inventario.to_excel('inventario_con_calculos.xlsx', index=False)
  from google.colab import files
  files.download('inventario_con_calculos.xlsx')