# -*- coding: utf-8 -*-
"""Calculos inventario Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTnTkmhUJ-faopoBrVJp1NGDtJk2u0-_
"""

# @title Importación de Librerias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import os

#@title FASE 1CARGA DE FACTURAS
facturas = [
    {
        "periodo": 1,
        "fecha_inicio": "2025-01-15",
        "fecha_fin": "2025-03-20",
        "consumo_total_kwh": 623,
        "valor_factura": 95775.08,
        "tarifa_promedio": 153.7321
    }
]

# --- FUNCIÓN DE COMPARACIÓN Y REGISTRO DE ERRORES ---
def comparar_equipos_y_registrar_errores(json_path, equipos_df, campo_comparar="kwh_total_año", archivo_errores="errores_golden_test.txt", tolerancia=0.01):
    """
    Compara el campo 'campo_comparar' entre el JSON exportado y el DataFrame de cálculo.
    Registra las discrepancias en un archivo de errores.
    """
    # Cargar datos del JSON exportado
    with open(json_path, "r", encoding="utf-8") as f:
        equipos_json = json.load(f)

    # Convertir a DataFrame para facilitar la comparación
    df_json = pd.DataFrame(equipos_json)

    errores = []
    for _, row in equipos_df.iterrows():
        nombre = row["nombre"]
        # Buscar el equipo en el JSON exportado
        match = df_json[df_json["nombre"] == nombre]
        if match.empty:
            errores.append(f"Equipo no encontrado en JSON: {nombre}")
            continue
        valor_json = match.iloc[0].get(campo_comparar, None)
        valor_py = row.get(campo_comparar, None)
        if valor_json is None or valor_py is None:
            errores.append(f"Campo '{campo_comparar}' faltante para equipo: {nombre}")
            continue
        # Comparar con tolerancia
        if abs(valor_json - valor_py) > tolerancia:
            errores.append(f"Equipo: {nombre} | {campo_comparar} | Exportado: {valor_json} | Calculado: {valor_py} | Diferencia: {valor_json - valor_py}")

    # Registrar errores en archivo
    if errores:
        with open(archivo_errores, "w", encoding="utf-8") as f:
            f.write("# Errores de comparación golden test\n\n")
            for err in errores:
                f.write(err + "\n")
        print(f"Se encontraron {len(errores)} discrepancias. Ver '{archivo_errores}'.")
    else:
        print("No se encontraron discrepancias relevantes.")

factura_ejemplo = facturas[0]
consumo_total_kwh = factura_ejemplo['consumo_total_kwh']
valor_factura = factura_ejemplo['valor_factura']
tarifa_promedio = factura_ejemplo['tarifa_promedio']

print(f"Consumo total de kWh: {consumo_total_kwh}")
print(f"Tarifa promedio por kWh: {tarifa_promedio}")
print(f"Valor de la factura (consumo_total_kwh * tarifa_promedio): {consumo_total_kwh * tarifa_promedio:.2f}")
print(f"Valor de la factura directamente de los datos: {valor_factura:.2f}")

# La "valor_factura" es el coste total de energía que se te ha cobrado.

#@title FASE 2  CARGA DE EQUIPOS POR USUARIOS
#NOTA PARA IA - Aca inicialmente SON LOS DATOS QUE SE CARGAN EN LA DB, EN EL CUESTIONARIO DE EQUIPEMT PARA LAS ENTITIES
#LA IDEA ES QUE PARA CARGAR ESTO, SE DEBE CARGA LA PRIMERA FACTURA, POR CONSIGUIENTE SOLO SE TRABAJA CON CALCULOS MENSUALES, NO ANUALES
#tenemos un nuevo dato a manejar que es TIPO DE PROCESO, que no está en el laravel

equipos = [
    {
        "nombre": "Aire Acondicionado Split 3000 frigorías",
        "tipo de proceso": "Motor",
        "categoria": "Climatización",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 1300,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso": "Motor",
        "categoria": "Climatización",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
    },
    {
        "nombre": "Microondas 20L",
        "tipo de proceso":"Magnetrón",
        "categoria": "Cocina",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 700,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "cocina / comedor",
        "cantidad": 3,
        "potencia_watts": 12,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Tubo LED 18W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 18,
        "horas_por_dia": 10,
    },
    {
        "nombre": "TV LED 32",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 50,
        "horas_por_dia": 8,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Router WiFi",
        "tipo de proceso":"Electrónico",
        "categoria": "Comunicaciones",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 24,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Afeitadora Eléctrica",
        "tipo de proceso":"Motor",
        "categoria": "Electrodomésticos",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Secador de Pelo",
        "tipo de proceso":"Motor & Resistencia",
        "categoria": "Electrodoméstico",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 1800,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,

    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
    },
    {
        "nombre": "TV LED 43",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 80,
        "horas_por_dia": 8,
    },
    {
        "nombre": "PC de Escritorio (Gaming)",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 400,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Monitor LED 27",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Omar",
        "cantidad": 2,
        "potencia_watts": 35,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Tira LED 5 metros",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 24,
        "horas_por_dia": 3,
    },
    {
        "nombre": "Aire Acondicionado Portátil",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 1200,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara LED 12W",
        "categoria": "Iluminación",
        "tipo de proceso":"Electroluminiscencia",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 4,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Hall",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Reflector LED 50W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Fondo",
        "cantidad": 1,
        "potencia_watts": 15,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara Halógena 50W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Vereda",
        "cantidad": 1,
        "potencia_watts": 50,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Cortadora de Fiambre",
        "tipo de proceso":"Motor",
        "categoria": "Cocina",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 250,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Heladera con Freezer (Cíclica)",
        "tipo de proceso":"Motor",
        "categoria": "Refrigeración",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 120,
        "horas_por_dia": 24,
    },
    {
        "nombre": "Lavarropas Automático 8kg",
        "tipo de proceso":"Motor & Resistencia",
        "categoria": "Lavado",
        "ubicacion": "Lavadero",
        "cantidad": 1,
        "potencia_watts": 650,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Cargador de Celular",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Comunicación",
        "ubicacion": "Portátiles",
        "cantidad": 3,
        "potencia_watts": 10,
        "horas_por_dia": 1,
    },
    {
        "nombre": "Notebook 14",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Portátiles",
        "cantidad": 1,
        "potencia_watts": 45,
        "horas_por_dia": 5
    }
]

# @title Parametrización de Datos de la tabla de Factor de Carga y Eficiencia - Formato estandar && Armar seeder para lograr cubrir todas las parametrizaciones
import pandas as pd

data = {
    'tipo de proceso': ['Motor', 'Resistencia', 'Electrónico', 'Motor & Resistencia', 'Magnetrón', 'Electroluminiscencia'],
    'factor de carga': [0.7, 1, 0.7, 0.8, 0.7, 1],
    'eficiencia': [0.9, 0.6, 0.8, 0.82, 0.6, 0.9]
}

tablaFQE = pd.DataFrame(data)
print(tablaFQE)

#@title Aca unimos por tipo de proceso y le damos el factor de carga y la eficiencia que pertenece, pero en el sistema podemos hacer que cuando elige el usuario una tipo de elemnto por defecto carga el tipo de proceso, y ahi calcula eficiencia y factor de carga
equipos_df = pd.DataFrame(equipos)
equipos_df = equipos_df.rename(columns={'tipo de proceso': 'tipo de proceso'})
print("DataFrame 'equipos_df' created and column 'tipo de proceso' renamed.")
equipos_df

# --- EJEMPLO DE USO DE LA FUNCIÓN DE COMPARACIÓN ---
# Ruta al JSON exportado desde Laravel
json_export_path = os.path.join("..", "storage", "app", "private", "exports", "equipments.json")
# Si el DataFrame tiene la columna 'kwh_total_año', se puede comparar directamente
if "kwh_total_año" in equipos_df.columns:
    comparar_equipos_y_registrar_errores(json_export_path, equipos_df, campo_comparar="kwh_total_año")
else:
    print("La columna 'kwh_total_año' no está disponible en el DataFrame de equipos.")

print("Aquí está el DataFrame fusionado 'equipos_merged_df' con 'factor de carga' y 'eficiencia':")
display(equipos_merged_df.head())
print("\nInformación detallada de 'equipos_merged_df':")

EnergiaConsumida = equipos_merged_df['horas_por_dia'] * equipos_merged_df['factor de carga'] * equipos_merged_df['cantidad'] * equipos_merged_df['potencia_watts'] / equipos_merged_df['eficiencia']
# Asignar la serie directamente al DataFrame como una nueva columna
equipos_merged_df['EnergiaConsumida_Wh'] = EnergiaConsumida

EnergiaUtilConsumida = equipos_merged_df['horas_por_dia'] * equipos_merged_df['factor de carga'] * equipos_merged_df['cantidad'] * equipos_merged_df['potencia_watts'] * equipos_merged_df['eficiencia']
# Asignar la serie directamente al DataFrame como una nueva columna
equipos_merged_df['EnergiaUtilConsumida_Wh'] = EnergiaUtilConsumida

print("Columnas 'EnergiaConsumida_Wh' y 'EnergiaUtilConsumida_Wh' agregadas a 'equipos_merged_df'.")

import pandas as pd

pd.set_option('display.max_columns', None) # Para mostrar todas las columnas

print("DataFrame 'equipos_merged_df' con las nuevas columnas de energía:")
display(equipos_merged_df)

from datetime import datetime

# Datos de la factura
factura_ejemplo = facturas[0]
tarifa_promedio = factura_ejemplo['tarifa_promedio']

# Calcular los días en el período de facturación
fecha_inicio = datetime.strptime(factura_ejemplo['fecha_inicio'], '%Y-%m-%d')
fecha_fin = datetime.strptime(factura_ejemplo['fecha_fin'], '%Y-%m-%d')
dias_en_periodo = (fecha_fin - fecha_inicio).days

# Datos del foco merge
potencia_foco_watts = 65
horas_uso_diario = 1

# Cálculo del consumo del foco
consumo_diario_wh = potencia_foco_watts * horas_uso_diario
consumo_diario_kwh = consumo_diario_wh / 1000  # Convertir a kWh

consumo_total_periodo_kwh = consumo_diario_kwh * dias_en_periodo

# Cálculo del costo monetario
costo_monetario_foco = consumo_total_periodo_kwh * tarifa_promedio

print(f"Tarifa promedio por kWh: {tarifa_promedio:.4f}")
print(f"Días en el período de facturación: {dias_en_periodo} días")
print(f"Consumo diario del foco: {consumo_diario_kwh:.3f} kWh")
print(f"Consumo total del foco en el período ({dias_en_periodo} días): {consumo_total_periodo_kwh:.3f} kWh")
print(f"Costo monetario del foco por el período: ${costo_monetario_foco:.2f}")

#@title aca logro sacar por mes el gasto de cada equipo, categoría, etc. esto no lo tenemos en el sistema

# Asegurarse de que 'dias_en_periodo' y 'tarifa_promedio' estén disponibles
# Si no lo están, se pueden obtener nuevamente de 'facturas'
from datetime import datetime

if 'dias_en_periodo' not in locals() or 'tarifa_promedio' not in locals():
    factura_ejemplo = facturas[0]
    tarifa_promedio = factura_ejemplo['tarifa_promedio']
    fecha_inicio = datetime.strptime(factura_ejemplo['fecha_inicio'], '%Y-%m-%d')
    fecha_fin = datetime.strptime(factura_ejemplo['fecha_fin'], '%Y-%m-%d')
    dias_en_periodo = (fecha_fin - fecha_inicio).days

# Calcular el consumo total en Wh para el período de facturación para cada equipo
equipos_merged_df['EnergiaConsumida_Wh_Periodo'] = equipos_merged_df['EnergiaConsumida_Wh'] * dias_en_periodo

# Convertir el consumo total del período a kWh
equipos_merged_df['EnergiaConsumida_kWh_Periodo'] = equipos_merged_df['EnergiaConsumida_Wh_Periodo'] / 1000

# Calcular el costo monetario para el período de facturación
equipos_merged_df['CostoMonetario_Periodo'] = equipos_merged_df['EnergiaConsumida_kWh_Periodo'] * tarifa_promedio

print("Columna 'CostoMonetario_Periodo' agregada a 'equipos_merged_df'.")
display(equipos_merged_df.round(2))

"""ETAPA DE MEJORAS, RECOMENDACIONES, ECT."""

equipos = [
    {
        "nombre": "Aire Acondicionado Split 3000 frigorías",
        "tipo de proceso": "Motor",
        "categoria": "Climatización",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 1300,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0

    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso": "Motor",
        "categoria": "Climatización",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Microondas 20L",
        "tipo de proceso":"Magnetrón",
        "categoria": "Cocina",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 700,
        "horas_por_dia": 1,
        "tiene_standby": 1,
        "standby_watts": 3
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "cocina / comedor",
        "cantidad": 3,
        "potencia_watts": 12,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Tubo LED 18W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 18,
        "horas_por_dia": 10,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "TV LED 32",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 50,
        "horas_por_dia": 8,
        "tiene_standby": 1,
        "standby_watts": 0.5
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Router WiFi",
        "tipo de proceso":"Electrónico",
        "categoria": "Comunicaciones",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 24,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Afeitadora Eléctrica",
        "tipo de proceso":"Motor",
        "categoria": "Electrodomésticos",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Secador de Pelo",
        "tipo de proceso":"Motor & Resistencia",
        "categoria": "Electrodoméstico",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 1800,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0

    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Mamá",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Ventilador de Techo",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 65,
        "horas_por_dia": 5,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "TV LED 43",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 80,
        "horas_por_dia": 8,
        "tiene_standby": 1,
        "standby_watts": 0.8
    },
    {
        "nombre": "PC de Escritorio (Gaming)",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 400,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Monitor LED 27",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Omar",
        "cantidad": 2,
        "potencia_watts": 35,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Tira LED 5 metros",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 24,
        "horas_por_dia": 3,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Aire Acondicionado Portátil",
        "tipo de proceso":"Motor",
        "categoria": "Climatización",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 1200,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "categoria": "Iluminación",
        "tipo de proceso":"Electroluminiscencia",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara de Escritorio LED",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Habitación Omar",
        "cantidad": 1,
        "potencia_watts": 10,
        "horas_por_dia": 4,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Hall",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Reflector LED 50W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Fondo",
        "cantidad": 1,
        "potencia_watts": 15,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara Halógena 50W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Vereda",
        "cantidad": 1,
        "potencia_watts": 50,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lámpara LED 12W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 12,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Cortadora de Fiambre",
        "tipo de proceso":"Motor",
        "categoria": "Cocina",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 250,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Heladera con Freezer (Cíclica)",
        "tipo de proceso":"Motor",
        "categoria": "Refrigeración",
        "ubicacion": "Garage",
        "cantidad": 1,
        "potencia_watts": 120,
        "horas_por_dia": 24,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Lavarropas Automático 8kg",
        "tipo de proceso":"Motor & Resistencia",
        "categoria": "Lavado",
        "ubicacion": "Lavadero",
        "cantidad": 1,
        "potencia_watts": 650,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Cargador de Celular",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Comunicación",
        "ubicacion": "Portátiles",
        "cantidad": 3,
        "potencia_watts": 10,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    {
        "nombre": "Notebook 14",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Portátiles",
        "cantidad": 1,
        "potencia_watts": 45,
        "horas_por_dia": 5,
        "tiene_standby": 0,
        "standby_watts": 0
    }
]

equipos_con_standby = [

      {
        "nombre": "Microondas 20L",
        "tipo de proceso":"Magnetrón",
        "categoria": "Cocina",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 700,
        "horas_por_dia": 1,
        "tiene_standby": 1,
        "standby_watts": 3
    },

    {
        "nombre": "TV LED 32",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Living",
        "cantidad": 1,
        "potencia_watts": 50,
        "horas_por_dia": 8,
        "tiene_standby": 1,
        "standby_watts": 0.5
    },
    {
        "nombre": "TV LED 43",
        "tipo de proceso":"Electrónico",
        "categoria": "Entretenimiento",
        "ubicacion": "Habitación Papá",
        "cantidad": 1,
        "potencia_watts": 80,
        "horas_por_dia": 8,
        "tiene_standby": 1,
        "standby_watts": 0.8
    },


]

print("Consumo Fantasma (Standby) y su Costo Monetario por Equipo:")

# Filtrar solo los equipos que tienen standby activo y mostrar las columnas relevantes
consumo_fantasma_df = equipos_merged_df[
    equipos_merged_df['tiene_standby'] == 1
][[
    'nombre',
    'horas_por_dia',
    'standby_horas_por_dia',
    'standby_watts',
    'standby_consumo_diario_Wh',
    'standby_consumo_periodo_kWh',
    'standby_costo_monetario_periodo'
]]

display(consumo_fantasma_df.round(2))

# Calcular y mostrar el total de consumo y costo fantasma
total_standby_kwh = consumo_fantasma_df['standby_consumo_periodo_kWh'].sum()
total_standby_costo = consumo_fantasma_df['standby_costo_monetario_periodo'].sum()

print(f"\nConsumo total fantasma en el período: {total_standby_kwh:.2f} kWh")
print(f"Costo total fantasma en el período: ${total_standby_costo:.2f}")

equipos_nuevos = [
    {
        "nombre": "Aire Acondicionado Split 3000 frigorías",
        "tipo de proceso": "Motor",
        "categoria": "Climatización",
        "ubicacion": "cocina / comedor",
        "cantidad": 1,
        "potencia_watts": 1000,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0

    },
    {
        "nombre": "Lámpara Halógena 50W",
        "tipo de proceso":"Electroluminiscencia",
        "categoria": "Iluminación",
        "ubicacion": "Vereda",
        "cantidad": 1,
        "potencia_watts": 15,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
     {
        "nombre": "Secador de Pelo",
        "tipo de proceso":"Motor & Resistencia",
        "categoria": "Electrodoméstico",
        "ubicacion": "Baño",
        "cantidad": 1,
        "potencia_watts": 800,
        "horas_por_dia": 1,
        "tiene_standby": 0,
        "standby_watts": 0
    },
    ]

import pandas as pd
from datetime import datetime

# --- 0. Asegurar que 'dias_en_periodo' y 'tarifa_promedio' estén disponibles ---
# Si no lo están, se pueden obtener nuevamente de 'facturas'
if 'dias_en_periodo' not in locals() or 'tarifa_promedio' not in locals():
    factura_ejemplo = facturas[0]
    tarifa_promedio = factura_ejemplo['tarifa_promedio']
    fecha_inicio = datetime.strptime(factura_ejemplo['fecha_inicio'], '%Y-%m-%d')
    fecha_fin = datetime.strptime(factura_ejemplo['fecha_fin'], '%Y-%m-%d')
    dias_en_periodo = (fecha_fin - fecha_inicio).days

# --- 1. Preparar el DataFrame de equipos nuevos ---

equipos_nuevos_df = pd.DataFrame(equipos_nuevos)

# Unir con tablaFQE para obtener factor de carga y eficiencia para los nuevos equipos
equipos_nuevos_merged_df = pd.merge(equipos_nuevos_df, tablaFQE, on='tipo de proceso', how='left')

# --- 2. Recalcular consumo y costo para equipos actuales (asegurar que las columnas existan) ---
# Este paso es crucial si equipos_merged_df fue recreado y perdió estas columnas

# Calcular EnergiaConsumida_Wh para equipos actuales
if 'EnergiaConsumida_Wh' not in equipos_merged_df.columns:
    equipos_merged_df['EnergiaConsumida_Wh'] = equipos_merged_df['horas_por_dia'] * \
                                              equipos_merged_df['factor de carga'] * \
                                              equipos_merged_df['cantidad'] * \
                                              equipos_merged_df['potencia_watts'] / \
                                              equipos_merged_df['eficiencia']

# Calcular consumo total en Wh para el período de facturación para cada equipo actual
if 'EnergiaConsumida_Wh_Periodo' not in equipos_merged_df.columns:
    equipos_merged_df['EnergiaConsumida_Wh_Periodo'] = equipos_merged_df['EnergiaConsumida_Wh'] * dias_en_periodo

# Convertir el consumo total del período a kWh para equipos actuales
if 'EnergiaConsumida_kWh_Periodo' not in equipos_merged_df.columns:
    equipos_merged_df['EnergiaConsumida_kWh_Periodo'] = equipos_merged_df['EnergiaConsumida_Wh_Periodo'] / 1000

# Calcular el costo monetario para el período de facturación para equipos actuales
if 'CostoMonetario_Periodo' not in equipos_merged_df.columns:
    equipos_merged_df['CostoMonetario_Periodo'] = equipos_merged_df['EnergiaConsumida_kWh_Periodo'] * tarifa_promedio


# --- 3. Calcular consumo y costo para equipos nuevos ---

# Calcular EnergiaConsumida_Wh para equipos nuevos
equipos_nuevos_merged_df['EnergiaConsumida_Wh'] = equipos_nuevos_merged_df['horas_por_dia'] * \
                                                  equipos_nuevos_merged_df['factor de carga'] * \
                                                  equipos_nuevos_merged_df['cantidad'] * \
                                                  equipos_nuevos_merged_df['potencia_watts'] / \
                                                  equipos_nuevos_merged_df['eficiencia']

# Calcular consumo total en Wh para el período de facturación para cada equipo nuevo
equipos_nuevos_merged_df['EnergiaConsumida_Wh_Periodo'] = equipos_nuevos_merged_df['EnergiaConsumida_Wh'] * dias_en_periodo

# Convertir el consumo total del período a kWh para equipos nuevos
equipos_nuevos_merged_df['EnergiaConsumida_kWh_Periodo'] = equipos_nuevos_merged_df['EnergiaConsumida_Wh_Periodo'] / 1000

# Calcular el costo monetario para el período de facturación para equipos nuevos
equipos_nuevos_merged_df['CostoMonetario_Periodo_NUEVO'] = equipos_nuevos_merged_df['EnergiaConsumida_kWh_Periodo'] * tarifa_promedio

# --- 4. Extraer costos de equipos actuales para comparación ---

# Filtrar los equipos actuales que tienen contraparte en los nuevos equipos
nombres_equipos_a_comparar = equipos_nuevos_merged_df['nombre'].tolist()
equipos_actuales_para_comparar = equipos_merged_df[
    equipos_merged_df['nombre'].isin(nombres_equipos_a_comparar)
].copy()

# Seleccionar y renombrar columnas relevantes de los equipos actuales
equipos_actuales_para_comparar = equipos_actuales_para_comparar[[
    'nombre', 'potencia_watts', 'CostoMonetario_Periodo'
]]
equipos_actuales_para_comparar = equipos_actuales_para_comparar.rename(columns={
    'potencia_watts': 'potencia_watts_ACTUAL',
    'CostoMonetario_Periodo': 'CostoMonetario_Periodo_ACTUAL'
})

# --- 5. Unir los datos para la comparación y calcular el ahorro ---

# Seleccionar columnas relevantes de los nuevos equipos para la unión
equipos_nuevos_comparacion = equipos_nuevos_merged_df[[
    'nombre', 'potencia_watts', 'CostoMonetario_Periodo_NUEVO'
]]
equipos_nuevos_comparacion = equipos_nuevos_comparacion.rename(columns={
    'potencia_watts': 'potencia_watts_NUEVO'
})

# Realizar el merge para tener ambos costos en un solo DataFrame
comparacion_df = pd.merge(
    equipos_actuales_para_comparar,
    equipos_nuevos_comparacion,
    on='nombre',
    how='inner'
)

# Calcular el ahorro monetario
comparacion_df['Ahorro_Monetario_Periodo'] = comparacion_df['CostoMonetario_Periodo_ACTUAL'] - comparacion_df['CostoMonetario_Periodo_NUEVO']

# --- 6. Mostrar los resultados ---

print("\n--- Análisis de Ahorro con Equipos Nuevos y Más Eficientes ---\n")
print("Comparación del costo por período de facturación:\n")
display(comparacion_df.round(2))

total_ahorro = comparacion_df['Ahorro_Monetario_Periodo'].sum()
print(f"\nEl ahorro monetario total estimado por período de facturación al cambiar a los equipos nuevos es: ${total_ahorro:.2f}")