# -*- coding: utf-8 -*-
"""Calculos Mejoras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16MewT6xBSbkHFw5Qzt-b1iyheDHJXDUd
"""

# @title Importación de Librerias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

CostoUnitario = 19.45

"""Aplicar las ecuaciones en forma general"""

# @title Parametrización de Datos de la tabla de Factor de Carga y Eficiencia - Formato estandar && no definitivo -  INVESTIGAR
data = {
    'Tipo de proceso': ['Motor', 'Resistencia', 'Electrónico', 'Motor & Resistencia', 'Magnetrón', 'Electroluminiscencia'],
    'Factor de Carga': [0.7, 1, 0.7, 0.8, 0.7, 1],
    'Eficiencia': [0.9, 0.6, 0.8, 0.82, 0.6, 0.9]
}

tablaFQE = pd.DataFrame(data)
print(tablaFQE)

# @title Carga de datos del Inventario General con mejoras

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

inventario_df = pd.read_excel('/content/drive/MyDrive/Modo Ahorro - Proyecto /Calculos/Calculos inventarios/mejoras.xlsx')

print(inventario_df.head())

# @title Mergue con Uso y tipo de proceso para normalizar Factor de Carga y Eficiencia - INVESTIGAR SI ESTÁ BIEN
inventario_m = pd.merge(inventario_df, tablaFQE, on='Tipo de proceso', how='left' )
inventario_m.head(5)

# @title Equipos con Estado de mejoras

mejoras = inventario_m[inventario_m['Estado'] == 'Mejora']
mejoras

# @title Equipos con Estado de Sugerencia
sugerencias = inventario_m[inventario_m['Estado'] == 'Sugerencia']
sugerencias

# @title Eleminar del inventario_m  a quitar
inventario_m = inventario_m[inventario_m['Finalidad'] != 'Quitar']
print(inventario_m.head())



inventario_m

# @title Cálculo de Energía Secundaria Consumida
inventario_m['Energia Secundaria Consumida'] = round((inventario_m['Horas de uso [h/año]'] * inventario_m['Factor de Carga']* inventario_m['Cantidad de equipos'] * inventario_m['Consumo Nominal']) / inventario_m['Eficiencia'], 2)
inventario_m.head(5)

inventario_m['Energia Util Consumida'] = inventario_m['Horas de uso [h/año]'] * inventario_m['Factor de Carga']* inventario_m['Cantidad de equipos'] * inventario_m['Consumo Nominal']
inventario_m.head(5)



# @title Distibución del consumo nominal
custom_palette = sns.color_palette("pastel")
sns.histplot(data=inventario_m, x='Consumo Nominal', bins=15, color=custom_palette[0])
plt.title('Distribución del consumo nominal')
plt.xlabel('Consumo Nominal (en la unidad correspondiente)')
plt.ylabel('Frecuencia')

sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

from matplotlib import pyplot as plt
inventario_m['Cantidad de equipos'].plot(kind='hist', bins=20, title='Cantidad de equipos')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
inventario_m['Horas de uso [h/año]'].plot(kind='hist', bins=20, title='Horas de uso [h/año]')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
inventario_m['Factor de Carga'].plot(kind='hist', bins=20, title='Factor de Carga')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
inventario_m.groupby('Uso)').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
inventario_m.groupby('Tipo de proceso').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
inventario_m.plot(kind='scatter', x='Consumo Nominal', y='Cantidad de equipos', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Tipo de proceso'].value_counts()
    for x_label, grp in inventario_m.groupby('Uso)')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Uso)')
_ = plt.ylabel('Tipo de proceso')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(inventario_m['Tipo de proceso'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario_m, x='Consumo Nominal', y='Tipo de proceso', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(inventario_m['Uso)'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario_m, x='Consumo Nominal', y='Uso)', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(inventario_m['Uso)'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario_m, x='Cantidad de equipos', y='Uso)', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(inventario_m['Tipo de proceso'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(inventario_m, x='Cantidad de equipos', y='Tipo de proceso', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

inventario_m['Costo $ Consumo'] = round(inventario_m['Energia Secundaria Consumida'] * CostoUnitario, 2)
inventario_m

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Consumo Nominal', y='Costo $ Consumo', data=inventario_m)
plt.xlabel('Consumo Nominal (kW)')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Consumo Nominal y Costo de Consumo')
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Cantidad de equipos', y='Costo $ Consumo', data=inventario_m)
plt.xlabel('Cantidad de equipos')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Cantidad de equipos y Costo de Consumo')
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Horas de uso [h/año]', y='Costo $ Consumo', data=inventario_m)
plt.xlabel('Horas de uso [h/año]')
plt.ylabel('Costo $ Consumo')
plt.title('Relación entre Horas de uso y Costo de Consumo')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Tipo de proceso', y='Costo $ Consumo', data=inventario_m)
plt.xlabel('Tipo de proceso')
plt.ylabel('Costo $ Consumo')
plt.title('Costo de Consumo por Tipo de proceso')
plt.xticks(rotation=45, ha='right')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Uso)', y='Costo $ Consumo', data=inventario_m)
plt.xlabel('Uso)')
plt.ylabel('Costo $ Consumo')
plt.title('Costo de Consumo por Uso)')
plt.xticks(rotation=45, ha='right')
plt.show()

# @title DESCARGA DE INVENTARIO CON CALCULOS - modificar valor de descarga por "Si" y ejecutar
descargar="No"
if descargar=="Si":
  inventario_m.to_excel('inventario_con_mejoras.xlsx', index=False)
  from google.colab import files
  files.download('inventario_con_calculos.xlsx')